#########################################################
#                                                       #
#                 LEAVING HOME                          #
#                                                       #
#########################################################

- alias: Leaving Home
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.adam_home_presence
    - platform: state
      entity_id: group.amy_home_presence
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states('group.adam_home_presence') != 'home' }}"
      - condition: template
        value_template: "{{ states('group.amy_home_presence') != 'home' }}"
      - condition: template  
        value_template: "{{ states('input_boolean.guest_mode') != 'on' }}"
  action:
    - service: switch.turn_off
      entity_id:
        - switch.kuled1
        - switch.kuled2
        - switch.basic1
    - service: light.turn_off
      entity_id:
        - light.tradfri_bulb_e26_ws_opal_980lm_3
        - light.tradfri_bulb_e26_ws_opal_980lm_2_2
        - light.yeelightrgb2

########################################################
#                                                      #
#             END OF CONFIGURATION FILE                #
#                                                      #
########################################################
